"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#e3a3d2)\
[ 󰆍 ](bg:#e3a3d2 fg:#090c0c)\
[](bg:#f076c0 fg:#e3a3d2)\
$directory\
[](fg:#f076c0 bg:#60395d)\
$git_branch\
$git_status\
[](fg:#60395d bg:#362134)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#362134 bg:#301d2d)\
$time\
[ ](fg:#301d2d)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#f076c0"
format = "[ $path ]($style)"
truncation_length = 5

[git_branch]
style = "bg:#60395d"
format = '[[ $symbol $branch ](fg:#f076c0 bg:#60395d)]($style)'

[git_status]
style = "bg:#60395d"
format = '[[($all_status$ahead_behind )](fg:#f076c0 bg:#60395d)]($style)'

[time]
disabled = false
style = "bg:#301d2d"
format = '[[  $time ](fg:#cba0c5 bg:#301d2d)]($style)'
